config/routes.rb
Rails.application.routes.draw do

  get 'home/index', to: 'home#index', as: 'home'
  root to: 'home#index'

  resources :users, :except => [:index]
  resources :projects
  resources :sessions, :only => [:new, :create, :destroy]
  resources :bugs 

  put 'solve/:id', to: 'bugs#solve', as: 'solve'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	# Validates the password, ensuring that password and password confirmation are equal. Also ensures that the password wont be blank
	has_secure_password

	# Email format
	EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\Z/i

	# Name can't be blank and length needs to be min 3 and max 20
	# Email can't be blank, must be unique and have the correct format
  	validates :name, :presence => true, :length => { :in => 3..20 }
  	validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :save_login_state, :only => [:new, :create]
	before_action :authenticate_user, :only => [:show, :edit, :update, :destroy]
	
	# GET /users/new
	def new
		@user = User.new
	end

	# POST /users
	def create
		@user = User.new(allowed_params_create)
		if @user.save
			redirect_to root_url, notice: "Thank you for signing up!"
		else
			render :new
		end
	end

	# GET /users/1
	def show
		# params[:id] comes from the URL: /users/:id
		@user = User.find(params[:id])
	end

  	# GET /users/1/edit
	def edit
		@user = User.find(params[:id])
	end

	# PATCH/PUT /users/1
	def update
		@user = User.find(params[:id])
		if @user.update_attributes(allowed_params_edit)
			redirect_to @user, notice: "Account has been updated!"
		else
			render :edit
		end
	end

	# DELETE /users/1
	def destroy
		# Destroy current user and all dependencies
		if session[:user_id]
			@current_user = User.find session[:user_id]

			# Delete all projects and bugs created by the user 
			Bug.where(user_id: @current_user.id).each do |bug|
				bug.destroy
			end

			
			Project.where(user_id: @current_user.id).each do |project|
				project.destroy
			end

			# Delete user and sign out
			@current_user.destroy
			session[:user_id] = nil
			redirect_to home_path
		end
	end

	# Params allowed for create a new user. Added password confirmation.
	private
	def allowed_params_create
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

	# Params allowed to be changed by the user
	private
	def allowed_params_edit
		params.require(:user).permit(:name, :email)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
<div class="error_explanation">
  The form contains <%= pluralize(@user.errors.count, "error") %>. 
  <div class="error_list">
    <ol>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ol>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>

<%= form_for @user do |f| %>

<!--List and show all form's error messages-->
<%= render 'error_messages' %>

<!--Form for editing-->
<ul class="form-style-1">
	<li>
		<%= f.label :name, 'Name' %>
		<%= f.text_field :name, placeholder: "What's your name?" %>
	</li>

	<li>
		<%= f.label :name, 'Name' %>
		<%= f.email_field :email, placeholder: "What's your e-mail address?" %>
	</li>

<li><%= f.submit 'Submit', class: 'submit-bnt' %></li>
</ul>

<% end %>

<!--Link to return to account page-->
<%= link_to "Return", user_path(@user) %>

app/views/users/new.html.erb
<!--Form for login-->
<div class="login-page">
  <div class="form">

    <%= form_for @user do |f| %>
    
    <!--List and show all form's error messages-->
    <%= render 'error_messages' %>

      <%= f.text_field :name, placeholder: "name", class: 'field'%>

      <%= f.email_field :email, placeholder: "email address", class: 'field' %>

      <%= f.password_field :password, placeholder: "password", class: 'field' %>

      <%= f.password_field :password_confirmation, placeholder: "confirm password", class: 'field' %>

      <%= f.submit "Sign up", class: 'form-bnt' %>

      <!--Link to signup page-->
      <p class="message">Already registered? <%= link_to "Log In", login_path %> </p>

    <% end %>
    
  </div>
</div>

app/views/users/show.html.erb
<!--Shows the current user name and email address-->
<h1>Hello, <%= @user.name %>!</h1>

<p>Here is your recent account configuration.</p>
<p><strong>Email address:</strong> <%= @user.email %></p>

<!--Links to edit/delete account (only name and email) and to home page-->
<button class="button"><%= link_to "Edit Account", edit_user_path(@user) %></button>
<button class="button"><%= link_to 'Delete', user_path(@user), method: :delete, data:{ confirm: 'Are you sure?'} %></button>