config/routes.rb
Rails.application.routes.draw do

  get 'home/index', to: 'home#index', as: 'home'
  root to: 'home#index'

  resources :users, :except => [:index]
  resources :projects
  resources :sessions, :only => [:new, :create, :destroy]
  resources :bugs 

  put 'solve/:id', to: 'bugs#solve', as: 'solve'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord

	# Name can't be blank and also needs to be min 3 and max 30
	# Budget and Start date can't be blank
	# Description can be left in blank
	# User id can't be nil 
	# Name and description must be unique. Can't have two projects that are the same

  	validates :name, :presence => true, :uniqueness => true, :length => { :in => 3..30 }
  	validates :description, :uniqueness => true
  	validates :budget, :presence => true
  	validates :start_date, :presence => true
  	validates :user_id, :presence => true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user
  
    # GET /projects
  def index
  	@projects = Project.all

    # Recover the user in the current session
    @current_user = User.find session[:user_id]

    current_user_id = @current_user.id

    # Only show the user's projects
    @projects = Project.where(user_id: current_user_id)
  end

  # GET /projects/new
  def new
    @project = Project.new 
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    # Recover the user in the current session
    @current_user = User.find session[:user_id]
    @project.user_id = @current_user.id
    
    if @project.save
      redirect_to @project, notice: "Project created successfully!"
    else
      render :new
    end
  end

  # GET /projects/1
  def show
  	@project = Project.find(params[:id])
  end

  # GET /projects/1/edit
  def edit
  	@project = Project.find(params[:id])
  end

  # PATCH/PUT /projects/1
  def update
  	@project = Project.find(params[:id])
  	if @project.update_attributes(project_params)
  		redirect_to @project, notice: "Project has been updated!"
  	else
  		render :edit
  	end
  end

  # DELETE /projects/1
  def destroy
    @project = Project.find(params[:id])

    # Delete all bugs from this project
    Bug.where(project_id: @project.id).each do |bug|
      bug.destroy
    end

    @project.destroy
    redirect_to projects_path
  end

  # Params allowed to create a new project
  private
  def project_params
  	params.require(:project).permit(:name, :description, :budget, :start_date)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

<!--List and show all error messages-->
<% if @project.errors.any? %>
<div class="error_messages">
	<h2>Form is invalid</h2>
	<ul>
		<% @project.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<!--Form's field-->
<ul class="form-style-1">
	<li>
		<%= f.label :name, 'Project Name' %>
		<%= f.text_field :name, placeholder: "What the name of your project?", class: "field-long" %>
	</li>

	<li>
		<%= f.label :description, 'Project Description' %>
		<%= f.text_area :description, placeholder: "What your project will do?", class: "field-long field-textarea" %>
	</li>

	<li>
		<%= f.label :budget, 'Project Budget' %>
		<%= f.number_field :budget, placeholder: "How much it will cost?", class: "field-long" %>
	</li>

	<li>
		<%= f.label :start_date, 'Start Date' %>
		<%= f.date_field :start_date, as: :date, placeholder: "dd/mm/yyyy" %>
	</li>

	<li><%= f.submit 'Submit', class: 'submit-bnt' %></li>
</ul>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<!--The partial form will be rendered-->
<%= render "form", project: @project %>

<!--Link to return to all projects-->
<p><%= link_to "Return", project_path(@project) %></p>

app/views/projects/index.html.erb
<h1>Projects</h1>

<!--Check if the current user has any records-->
<% @current_user = User.find session[:user_id]%>

<% if Project.where(user_id: @current_user.id).any? %>

<p>Here is all projects that you created.</p>
<!--Table to display all projects (created by the current user in a session) and it's attributes-->
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Budget</th>
      <th>Start Date</th>
      <th>Actions</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  	<tbody>
	<% @projects.each do |project| %>
		<tr>
			<td><%= project.name %></td>
			<td><%= project.description %></td>
			<td><%= project.budget %></td>
			<td><%= project.start_date %></td>
			<td>
        <span><i class="fa fa-search"></i><%= link_to "View", project%></span>
      </td>
		</tr>
	<% end %>
	</tbody>
</table>

<% else %>

<p>There's no project yet. Create a new one!</p>

<% end %>

<!--Links to return to home page or create a new project-->
<button class="button"><%= link_to 'New Project', new_project_path %></button>

app/views/projects/new.html.erb
<h1>New Project</h1>

<!--The partial form will be rendered-->
<%= render 'form', project: @project %>

<!--Link to return to all projects-->
<%= link_to "Return", projects_path %>

app/views/projects/show.html.erb
<!--Show all project's attributes-->
<h1><%= @project.name %></h1>

<p><strong>Description:</strong> <%= @project.description %></p>
<p><strong>Budget:</strong> <%= @project.budget %></p>
<p><strong>Start date:</strong> <%= @project.start_date %></p>

<!--Links to edit/delete the project or return to all projects-->
<button class="button"><%= link_to "All Projects", projects_path %></button>
<button class="button"><%= link_to "Edit", edit_project_path(@project) %></button>
<button class="button"><%= link_to 'Delete', project_path(@project), method: :delete, data:{ confirm: 'Are you sure?'} %></button>	