config/routes.rb
Rails.application.routes.draw do

  get 'home/index', to: 'home#index', as: 'home'
  root to: 'home#index'

  resources :users, :except => [:index]
  resources :projects
  resources :sessions, :only => [:new, :create, :destroy]
  resources :bugs 

  put 'solve/:id', to: 'bugs#solve', as: 'solve'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bug.rb
class Bug < ApplicationRecord

	# Name and description must be unique to make sure that all bugs are different
	validates :name, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
	validates :description, :uniqueness => true

	# Can exists different bugs with the same type. Also can exists different bugs in the same project
	validates :bug_type, :presence => true, :length => { :in => 3..30 }
	validates :project_id, :presence => true
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :authenticate_user

  # GET /bugs
  def index
    @bugs = Bug.all

    # Recover the user in the current session
    @current_user = User.find session[:user_id]

    current_user_id = @current_user.id

    # Only show the user's projects
    @bugs = Bug.where(user_id: current_user_id)
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
    @bug.solve = false # Set solve to false when initialized
  end

  # POST /bugs
  def create
    @bug = Bug.new(bug_params)
    @bug.solve = false # Set solve to false when initialized

    # Recover the user in the current session
    @current_user = User.find session[:user_id]
    @bug.user_id = @current_user.id

    if @bug.save

      # Create a message with the bug's information
      message = ""
      message << "*New bug created!*\n"
      message << "*Name:* #{@bug.name}\n"
      message << "*Type:* #{@bug.bug_type}\n"
      message << "*Description:* ```#{@bug.description}``` \n"

      # Create a new Slack notifier
      notifier = Slack::Notifier.new "https://hooks.slack.com/services/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",
      channel: "desafio-dev-mariana"

      # Send the message to Slack
      notifier.ping message

      flash.now.alert = "Bug created successfully!"
      redirect_to @bug
    else
      render :new
    end
  end

  # GET /bugs/1
  def show
    @bug = Bug.find(params[:id])
  end

  # GET /bugs/1/edit
  def edit
    @bug = Bug.find(params[:id])
  end

  # PATCH/PUT /bugs/1
  def update
    @bug = Bug.find(params[:id])
    if @bug.update_attributes(bug_params)
      flash.now.alert = "Bug has been updated!"
      redirect_to @bug
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @bug = Bug.find(params[:id])
    @bug.destroy
    redirect_to bugs_path
  end

  # PUT /bugs/1
  def solve
    @bug = Bug.find(params[:id])
    if @bug.update_attribute(:solve, true)

      # Create a message with the bug's information
      message = ""
      message << "*Bug solved!*\n"
      message << "*State:* Solved\n"
      message << "*Name:* #{@bug.name}\n"
      message << "*Type:* #{@bug.bug_type}\n"
      message << "*Description:* ```#{@bug.description}``` \n"

      # Create a new Slack notifier
      notifier = Slack::Notifier.new "https://hooks.slack.com/services/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",
      channel: "desafio-dev-mariana"

      # Send the message to Slack
      notifier.ping message

      redirect_to @bug, notice: "Bug has been solved!"
    else
      redirect_to bugs_path, notice: "Couldn't solve bug" 
    end
  end

  private
  # Params allowed to be changed by the user
  def bug_params
    params.require(:bug).permit(:name, :bug_type, :description, :project_id)
  end
end

app/helpers/bugs_helper.rb
module BugsHelper

	# Display the value of attribute solve 
	def bool_to_str(value)
		if value == true
			"Yes"
		elsif value == false
			"No"
		elsif value == nil
			"Nil"
		end
	end

end

app/views/bugs/_form.html.erb
<%= form_for @bug do |f| %>

<!--List and show all error messages-->
<% if @bug.errors.any? %>
<div class="error_messages">
  <h2>Form is invalid</h2>
  <ul>
    <% @bug.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<!--Form's field-->
<ul class="form-style-1">

  <li>
    <%= f.label :name, 'Bug Name' %>
    <%= f.text_field :name, placeholder: "What the name of this bug?" %>
  </li>

  <li>
    <%= f.label :bug_type, 'Bug Type' %>
    <%= f.text_field :bug_type, placeholder: "What is this bug's type?" %>
  </li>

  <li>
    <%= f.label :description, 'Bug Description' %>
    <%= f.text_area :description, placeholder: "What this bug cause?" %>
  </li>

  <li>
    <%= f.label :project_id, 'Project' %>
    <% @current_user = User.find session[:user_id] %>
    <%= f.select :project_id, Project.where(user_id: @current_user.id).collect {|p| [ p.name, p.id] }, prompt: 'From what project is this bug?' %>
  </li>

  <li><%= f.submit 'Submit', class: 'submit-bnt' %></li>
</ul>

<% end %>

app/views/bugs/edit.html.erb
<h1>Editing Bug</h1>

<!--The partial form will be rendered-->
<%= render "form", bug: @bug %>

<!--Link to return to all bugs-->
<%= link_to "Return", bugs_path %>

app/views/bugs/index.html.erb
<h1>Bugs</h1>

<!--Check if the current user has any records-->
<% @current_user = User.find session[:user_id]%>

<% if Bug.where(user_id: @current_user.id).any? %>

<p>Here is all bugs that you created.</p> 

<!--Table to display all bugs (created by the current user in a session) and it's attributes-->
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Description</th>
      <th>Solve</th>
      <th>Project</th>
      <th>Actions</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
      <tr>
        <td><%= bug.name %></td>
        <td><%= bug.bug_type %></td>
        <td><%= bug.description %></td>
        <td><%= bool_to_str(bug.solve) %></td>
        <td><%= Project.find_by(id: bug.project_id).name %></td>
        <td>
          <span><i class="fa fa-search"></i><%= link_to "View", bug%></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>

<p>There's no bug yet. Create a new one!</p>

<% end %>

<!--Links to return to home page or create a new bug-->
<button class="button"><%= link_to 'New Bug', new_bug_path %></button>

app/views/bugs/new.html.erb
<h1>New Bug</h1>

<!--The partial form will be rendered-->
<%= render "form", bug: @bug %>

<!--Link to return to all bugs-->
<%= link_to "Return", bugs_path %>

app/views/bugs/show.html.erb
<!--Show all bug's attributes-->
<h1><%= @bug.name %></h1>

<p>Type: <%= @bug.bug_type %></p>

<p>Description: <%= @bug.description %></p>

<p>Project: <%= Project.find_by(id: @bug.project_id).name %></p>

<p>Created by: <%= User.find_by(id: @bug.user_id).name %></p>

<p>Solve: <%= bool_to_str(@bug.solve) %></p>

<!--Links to edit/delete/solve the bug or return to all bugs-->
<button class="button"><%= link_to 'All Bugs', bugs_path %></button>

<!--Only shows edit/solve/delete if a bug is not yet solved-->
<% if @bug.solve == false %>
  <button class="button"><%= link_to 'Edit', edit_bug_path(@bug) %></button>
  <button class="button"><%= link_to "Solve", solve_path(@bug), method: :put %></button>
<% end %>

<button class="button"><%= link_to 'Delete', bug_path(@bug), method: :delete, data:{ confirm: 'Are you sure?'} %></button>