config/routes.rb
Rails.application.routes.draw do

  get 'home/index', to: 'home#index', as: 'home'
  root to: 'home#index'

  resources :users, :except => [:index]
  resources :projects
  resources :sessions, :only => [:new, :create, :destroy]
  resources :bugs 

  put 'solve/:id', to: 'bugs#solve', as: 'solve'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_messages.html.erb
<div>
	<div class="alert">
		<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, class: "inner" %>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Challenge Dev Mariana</title>
  <%= stylesheet_link_tag "main", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<div class="header">
  <%= render 'layouts/flash_messages' if !flash.empty? %>
</div>

<div class="main">
	<div class="content">
		<div class="topnav">
			<% if logged_in? %>
			<ul>
					<li><%= link_to 'Home', home_path%></li>
					<li><%= link_to 'Projects', projects_path%></i>
					<li><%= link_to 'Bugs', bugs_path%></li>
					<li>
						<%@current_user = User.find session[:user_id]%>
						<%= link_to 'Manage account', user_path(@current_user.id)%>
					</li>
					<li id="logout"><%= link_to 'Logout', logout_path%></li>
			</ul>
			<% else %>
				<h1>Project Managment</h1>
			<% end %>
		</div>

		<div class="slider"></div>
		<div class="information">
			<%= yield %>
		</div>
	</div>
</div>

</body>

</html>